export const roomRegistry = {
  intro: {
    id: "intro",
    route: "intro",
    title: "Intro Room",
    subtitle: "Start here and get oriented.",
    background: "/Generic_Home_1_Layer_1.png?v=16x16",
    foreground: "/Generic_Home_1_Layer_2_.png?v=16x16",
    spawnRatio: { x: 0.5, y: 0.43 },
    popOutPoints: {
      nav: { x: 0.52, y: 0.5 },
      fromProjects: { x: 0.28, y: 0.58 },
    },
    sectionId: "section-intro",
    interactables: [
      {
        id: "intro-scroll",
        type: "scroll",
        label: "Read Intro",
        x: 0.42,
        y: 0.18,
        radius: 24,
        contentId: "intro-card",
        openMode: "panel",
      },
      {
        id: "intro-desk",
        type: "desk",
        label: "Professional Desk",
        x: 0.61,
        y: 0.28,
        radius: 24,
        contentId: "intro-desk",
        openMode: "panel",
      },
      {
        id: "door-projects",
        type: "door",
        label: "Projects Door",
        x: 0.82,
        y: 0.52,
        radius: 22,
        roomId: "projects",
        openMode: "route",
      },
      {
        id: "door-linkedin",
        type: "door",
        label: "LinkedIn Door",
        x: 0.15,
        y: 0.6,
        radius: 21,
        href: "https://www.linkedin.com/in/",
        openMode: "external",
      },
    ],
  },
  projects: {
    id: "projects",
    route: "projects",
    title: "Projects Workshop",
    subtitle: "Major projects and technical highlights.",
    background: "/Generic_Home_1_Layer_1.png?v=16x16",
    foreground: "/Generic_Home_1_Layer_2_.png?v=16x16",
    spawnRatio: { x: 0.47, y: 0.53 },
    popOutPoints: {
      nav: { x: 0.54, y: 0.56 },
      fromIntro: { x: 0.72, y: 0.55 },
    },
    sectionId: "section-projects",
    interactables: [
      {
        id: "masters-thesis-board",
        type: "board",
        label: "Master's Thesis",
        x: 0.34,
        y: 0.2,
        radius: 24,
        contentId: "project-masters-thesis",
        openMode: "projectOverlay",
      },
      {
        id: "audio-project-shelf",
        type: "shelf",
        label: "Audio Project",
        x: 0.51,
        y: 0.2,
        radius: 24,
        contentId: "project-audio",
        openMode: "projectOverlay",
      },
      {
        id: "acoustic-cnn-desk",
        type: "desk",
        label: "Acoustic CNN project",
        x: 0.68,
        y: 0.24,
        radius: 24,
        contentId: "project-acoustic-cnn",
        openMode: "projectOverlay",
      },
      {
        id: "redirected-walking-board",
        type: "board",
        label: "Redirected Walking",
        x: 0.57,
        y: 0.7,
        radius: 24,
        contentId: "project-redirected-walking",
        openMode: "projectOverlay",
      },
      {
        id: "project-gallery-wall",
        type: "board",
        label: "Workshop Gallery",
        x: 0.39,
        y: 0.68,
        radius: 22,
        contentId: "project-gallery",
        openMode: "imageGallery",
      },
      {
        id: "project-pdf-scroll",
        type: "scroll",
        label: "Research PDF",
        x: 0.2,
        y: 0.52,
        radius: 20,
        contentId: "project-pdf-preview",
        openMode: "pdfPreview",
      },
      {
        id: "door-github",
        type: "door",
        label: "GitHub Door",
        x: 0.86,
        y: 0.48,
        radius: 20,
        href: "https://github.com",
        openMode: "external",
      },
      {
        id: "door-intro",
        type: "door",
        label: "Back To Intro",
        x: 0.18,
        y: 0.58,
        radius: 20,
        roomId: "intro",
        openMode: "route",
      },
    ],
  },
};

export const roomOrder = ["intro", "projects"];
